pretty = "*"

coolStory = True

while coolStory:
    print('\n')
    userStory = input("Do you know the password?")

    if userStory == "Hb8r,7a=8#Q&!jSe":
        word1 = input("Enter material: ")
        word2 = input("Enter body part: ")
        word3 = input("Enter adjective: ")
        word4 = input("Enter verb: ")
        word5 = input("Enter verb ending with 's': ")
        word6 = input("Enter adjective: ")
        word7 = input("Enter plural noun: ")
        word8 = input("Enter body part: ")
        word9 = input("Enter verb: ")
        word10 = input("Enter social group: ")
        word11 = input("Enter verb ending with 's': ")
        word12 = input("Enter general place: ")
        word13 = input("Enter verb ending with 's': ")
        word14 = input("Enter verb ending with 's': ")
        word15 = input("Enter adjective: ")
        word16 = input("Enter article of clothing: ")
        word17 = input("Enter gerund: ")
        line1 = ("I am " + word1 + " MAN")
        line2 = ("Has he lost his " + word2)
        line3 = ("Can he see or is he " + word3 + "?")
        line4 = ("Can he " + word4 + " at all,")
        line5 = ("Or if he " + word5 + " will he fall?")
        line6 = ("Is he " + word6 + " or dead?")
        line7 = ("Has he " + word7 + " within his " + word8 + " ?")
        line8 = ("We`ll just " + word9 + " him there")
        line9 = ("Why should we even care?")
        line10 = ("He was turned to " + word1)
        line11 = ("In the great magnetic field")
        line12 = ("When he traveled time")
        line13 = ("For the future of " + word10)
        line14 = ("Nobody " + word11 + " him")
        line15 = ("He just stares at the world")
        line16 = ("Planning his vengeance")
        line17 = ("That he will soon unfurl")
        line18 = ("Now the time is here")
        line19 = ("For " + word1 + " Man to spread fear")
        line20 = ("Vengeance from the " + word12)
        line21 = (word13 + " the people he once saved")
        line22 = ("Nobody " + word14 + " him")
        line23 = ("They just turn their heads")
        line24 = ("Nobody helps him")
        line25 = ("Now he has his revenge")
        line26 = (word15 + " " + word16 + " of lead")
        line27 = ("Fills his victims full of dread")
        line28 = (word17 + " as fast as they can")
        line29 = (word1 + " Man lives again")
        print("\n")
        print(pretty*35)
        print(line1)
        print(line2)
        print(line3)
        print(line4)
        print(line5)
        print(line6)
        print(line7)
        print(line8)
        print(line9)
        print(line10)
        print(line11)
        print(line12)
        print(line13)
        print(line14)
        print(line15)
        print(line16)
        print(line17)
        print(line18)
        print(line19)
        print(line20)
        print(line21)
        print(line22)
        print(line23)
        print(line24)
        print(line25)
        print(line26)
        print(line27)
        print(line28)
        print(line29)
        print(pretty*35)
    else:
        print('Sorry! Wrong Password!')
        trueStory = False